server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Não logar acessos comuns no stdout do container (deixa o log limpo).
    access_log off;

    # Cache agressivo pros assets com hash no nome (immutable).
    location ~* \.(?:js|css|png|jpe?g|gif|ico|svg|woff2?)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    # SPA fallback: qualquer rota desconhecida devolve o index.html para
    # o Angular Router resolver client-side.
    location / {
        try_files $uri $uri/ /index.html;
    }
}
