version: '3.8'

services:
  app:
    image: ${DOCKER_USERNAME}/analyzer:latest
    container_name: analyzer-app
    restart: always
    environment:
      - ANALYZER_SERVER_PORT=15600
      - ANALYZER_DATABASE_CONNECTION=jdbc:postgresql://db:5432/analyzer
      - ANALYZER_DATABASE_USER=${ANALYZER_DATABASE_USER}
      - ANALYZER_DATABASE_PASSWORD=${ANALYZER_DATABASE_PASSWORD}
      - ANALYZER_DISCORD_TOKEN=${ANALYZER_DISCORD_TOKEN}
      - ANALYZER_DISCORD_CLIENT_ID=${ANALYZER_DISCORD_CLIENT_ID}
      - ANALYZER_DISCORD_CLIENT_SECRET=${ANALYZER_DISCORD_CLIENT_SECRET}
      - ANALYZER_FRONTEND_URL=https://huntanalyzer.lbaba.com.br
      - ANALYZER_COOKIE_SECURE=true
      - ANALYZER_COOKIE_DOMAIN=lbaba.com.br
    depends_on:
      - db
    networks:
      - analyzer-network
      - proxy-net

  frontend:
    image: ${DOCKER_USERNAME}/analyzer-frontend:latest
    container_name: analyzer-frontend
    restart: always
    networks:
      - proxy-net


  db:
    image: postgres:16-alpine
    container_name: analyzer-db
    restart: always
    environment:
      POSTGRES_DB: analyzer
      POSTGRES_USER: ${ANALYZER_DATABASE_USER}
      POSTGRES_PASSWORD: ${ANALYZER_DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - analyzer-network

volumes:
  postgres_data:

networks:
  analyzer-network:
    driver: bridge
  proxy-net:
    external: true
