spring.application.name=tibia-analyzer
spring.datasource.url=${DATABASE_CONNECTION}
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
server.port=64064
discord.bot.token=${DISCORD_TOKEN}