spring.application.name=analyzer
spring.datasource.url=${ANALYZER_DATABASE_CONNECTION}
spring.datasource.username=${ANALYZER_DATABASE_USER}
spring.datasource.password=${ANALYZER_DATABASE_PASSWORD}
server.port=${ANALYZER_SERVER_PORT}
discord.bot.token=${ANALYZER_DISCORD_TOKEN}